# Generated by Django 5.2.8 on 2025-12-06 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='net_salary',
            new_name='net_salary_value',
        ),
    ]
